"""
This module provides the conversion from graph -> circuit -> line graph
"""

import networkx as nx
from qiskit import QuantumCircuit
from itertools import combinations

def createGraph(n):
    """
    Create a 3-regular graph with n nodes

    Args:
        n (int): The number of nodes

    Returns:
        nx.Graph: 3-regular graph
    """
    G = nx.random_regular_graph(3, n, seed=7)
    return G

def convertToCircuit(G):
    """
    Convert a 3-regular graph to a QAOA circuit

    Args:
        G (nx.Graph): Graph from createGraph()

    Returns:
        QuantumCircuit: QAOA Quantum Circuit
    """
    gamma = 0.5
    beta = 0.3
    n = len(G.nodes())
    circuit = QuantumCircuit(n)
    circuit.h(range(n))

    for u,v in G.edges():
        circuit.rzz(2*gamma, u, v)
    for i in range(n):
        circuit.h(i)
        circuit.rz(2*beta, i)
        circuit.h(i)

    return circuit

def convertToLineGraph(circuit):
    """
    Convert a quantum circuit into a line graph representation

    Args:
        circuit (QuantumCircuit): QuantumCircuit generated by createExampleCircuit()

    Returns:
        nx.Graph: line graph representation
    """
    LG = nx.Graph()
    idx = 0
    q_indices = dict()
    for i in range(circuit.num_qubits):
        q_indices[i] = i
    LG.add_nodes_from(q_indices.values())
    idx += circuit.num_qubits

    for instruction in circuit.data:
        qubits = []
        gate = instruction.operation

        for q in instruction.qubits:
            qubits.append(circuit.find_bit(q).index)

        inputs = []
        for q in qubits:
            inputs.append(q_indices[q])

        if gate.name == 'rz':
            new_idx = idx
            idx += 1
            q_indices[qubits[0]] = new_idx
            gate_idx = inputs + [new_idx]

        else:
            outputs = []
            for q in qubits:
                q_indices[q] = idx
                outputs.append(q_indices[q])
                idx += 1
            gate_idx = inputs + outputs

        LG.add_nodes_from(gate_idx)
        LG.add_edges_from(combinations(gate_idx, 2))
    return LG