import networkx as nx
from qiskit import QuantumCircuit
import math
import sys
import random
from itertools import combinations
import matplotlib.pyplot as plt
import numpy as np

def createCircuit(G):
    """
    Convert a 3-regular graph to a QAOA circuit

    Args:
        G (nx.Graph): Graph from createNodeGraph()

    Returns:
        QuantumCircuit: QAOA Quantum Circuit
    """
    gamma = 0.5
    beta = 0.3
    n = len(G.nodes())
    circuit = QuantumCircuit(n)
    circuit.h(range(n))

    for u,v in G.edges():
        circuit.rzz(2*gamma, u, v)
    for i in range(n):
        circuit.rx(2*beta, i)

    return circuit

def createGraph(n):
    """
    Create a 3-regular graph with 10 nodes

    Args:
        n (int): The number of nodes

    Returns:
        nx.Graph: 3-regular graph
    """
    G = nx.random_regular_graph(3, n)
    return G

def convertToLineGraph(circuit: QuantumCircuit):
    """
    Convert a quantum circuit into a line graph representation

    Args:
        circuit: QuantumCircuit generated by createExampleCircuit()

    Returns:
        nx.Graph: line graph representation
    """
    LG = nx.Graph()
    for i in range(circuit.num_qubits):
        LG.add_node(i)
    return LG

def contract(G, v):
    """
    Contract a tensor index by removing a node and turning its neighbors into a clique

    Args:
         G (nx.Graph): graph
         v (_Node): the node to be removed

    Returns:
          nx.Graph: copy of G after contracting node v
    """
    G_copy = G.copy()
    neighbors = list(G.neighbors(v))
    G.add_edges_from(combinations(neighbors, 2))
    G.remove_node(v)
    return G_copy

def greedy(G):
    min = sorted(G.nodes(), key=lambda v: G.degree(v))[0]

def rgreedy(G, tau, q):
    """
    Implementation of the randomized greedy ordering algorithm

    Args:
        G (nx.Graph): graph
        tau (float): parameter
        q (int): number of repetitions

    Returns:
        list[int], int, list[int]: the best ordering, its contraction width and a list of widths
    """
    bestOrder = None
    bestWidth = sys.maxsize
    bestNeighbors = []
    for i in range(q):
        order = []
        width = 0
        widths = []

        G_copy = G.copy()

        while G_copy.number_of_nodes() > 0:
            nodes = list(G_copy.nodes())
            weights = []
            prob = []
            # calculate probabilities for each node
            for v in nodes:
                num_neighbors = len(list(G_copy.neighbors(v)))
                w = math.exp(-1/tau * num_neighbors)
                weights.append(w)
            weightsSum = sum(weights)

            for w in weights:
                prob.append(w / weightsSum)

            v = random.choices(nodes, weights=prob)[0]

            width = max(width, len(list(G_copy.neighbors(v))))
            order.append(v)
            widths.append(len(list(G_copy.neighbors(v))))

            contract(G_copy, v)

        if width < bestWidth:
            bestWidth = width
            bestOrder = order
            bestNeighbors = widths
    return bestOrder, bestWidth, bestNeighbors

def plotNeighbors(widths):
    """
    Plot the number of neighbors

    Args:
        widths: The number of neighbors
    """
    x = range(len(widths))
    neighbors = plt.subplot(1,2,1)
    neighbors.plot(x, widths, color='red', linestyle='-')
    neighbors.set_title("Contraction width")
    neighbors.set_xlabel("Steps")
    neighbors.set_ylabel("Number of neighbors")

    cost = plt.subplot(1,2,2)
    cost.plot(x, np.exp2(widths), color='red', linestyle='-')
    cost.set_title("Computational cost")
    neighbors.set_xlabel("Steps")

    plt.show()

def findOptimalS(G, widths, order):
    """
    Find the optimal step s

    Args:
        G (nx.Graph): line graph
        widths (list[int]): the degrees of each node
        order (list[int]): the initial ordering

    Returns:
        list[int], int, list[int], int: new ordering with less contraction width, the width profile
        and the optimal step S at which to slice r highest vertices
    """
    peak = widths.index(max(widths))
    minCWidth = sys.maxsize
    optimalS = 0
    newWidths = []
    newOrdering = []

    for s in range(peak):
        G_copy = G.copy()

        for v in order[:s]:
            contract(G_copy, v)

        maxNeighbors = sorted(G_copy.nodes(), key=lambda v: G_copy.degree(v), reverse=True)[0]
        G_copy.remove_node(maxNeighbors)
        newOrder, width, neighbors = rgreedy(G_copy, 0.5, 25)
        if width < minCWidth:
            newOrdering = newOrder
            minCWidth = width
            newWidths = neighbors
            optimalS = s


    return newOrdering, minCWidth, newWidths, optimalS

def stepDependentSlicing(LG, order, n, r):
    """
    Slice a graph to find optimal step s

    Args:
        LG (nx.Graph): line graph
        order: ordering of which indices to contract based on rgreedy
        n: total number of indices to slice
        r: number of nodes to slice per step

    Returns:
        int: optimal s
        list[nodes]: which nodes to slice
    """
    pass




