import networkx as nx
from qiskit import QuantumCircuit
import math
import sys
import random
from itertools import combinations

def createExampleCircuit(G):
    """
    Converts the 4 node graph to a QAOA circuit from the paper for testing purposes

    Args:
        G: Graph from createNodeGraph()

    Returns:
        QuantumCircuit: QAOA Quantum Circuit
    """
    gamma = 0.5
    beta = 0.3
    circuit = QuantumCircuit(4)
    for i in range(4):
        circuit.h(i)

    for u,v in G.edges():
        circuit.rzz(2*gamma, u, v)

    for i in range(4):
        circuit.rx(2*beta, i)
    return circuit

def createNodeGraph():
    """
    Create a basic 4 node graph for testing purposes

    Returns:
        nx.Graph: 4-node graph
    """
    G = nx.random_regular_graph(3, 4)
    return G


def createGraph():
    """
    Creates a 3-regular graph with 10 nodes

    Returns:
        nx.Graph: 3-regular graph
    """
    G = nx.random_regular_graph(3, 10)
    return G

def convertToLineGraph(circuit: QuantumCircuit):
    """
    Convert a quantum circuit into a line graph representation

    Args:
        circuit: QuantumCircuit generated by createExampleCircuit()

    Returns:
        nx.Graph: line graph representation
    """
    LG = nx.Graph()
    for i in range(circuit.num_qubits):
        LG.add_node(i)
    return LG

def contract(G, v):
    """
    Contract a tensor index by removing a node and turning its neighbors into a clique

    Args:
         G (nx.Graph): graph
         v (_Node): the node to be removed

    Returns:
          nx.Graph: copy of G after contracting node v
    """
    G_copy = G.copy()
    neighbors = list(G.neighbors(v))
    G.add_edges_from(combinations(neighbors, 2))
    G.remove_node(v)
    return G_copy

def rgreedy(G, tau, q):
    """
    Implementation of the randomized greedy ordering algorithm

    Args:
        G (nx.Graph): graph
        tau (float): parameter
        q (int): number of repetitions

    Returns:
        list[nodes], int: the best ordering based on minimal contraction width
    """
    bestOrder = None
    bestWidth = sys.maxsize
    for i in range(q):
        order = []
        width = 0
        weights = []
        G_copy = G.copy()

        while G_copy.number_of_nodes() > 0:
            nodes = list(G_copy.nodes())

            # calculate probabilities for each node
            for v in nodes:
                num_neighbors = len(list(G_copy.neighbors(v)))
                w = math.exp(-1/tau * num_neighbors)
                weights.append(w)
            weightsSum = sum(weights)
            prob = []
            for w in weights:
                prob.append(w / weightsSum)

            v = random.choices(nodes, weights=prob)[0]

            width = max(width, len(list(G_copy.neighbors(v))))
            order.append(v)

            contract(G_copy, v)

        if width < bestWidth:
            bestWidth = width
            bestOrder = order
    return bestOrder, bestWidth




